### ISSUE TITLE
過去公開分（2017年5月、2017年6月）のPDFファイルを入手する

### ISSUE THREAD

**Issue by nyampire** [nyampire/jp_labor_act_illegal_list#10]
厚生労働省から譲渡することはできないという回答があった。

そのため、誰かの手元で保管しているものを譲ってもらう必要がある。

**Comment by nyampire** [comment]
国立国会図書館のWARPサービスにて、過去データを入手できる模様。

- [x] 2017年5月データ: [対応済み](http://warp.da.ndl.go.jp/info:ndljp/pid/10368290/www.mhlw.go.jp/kinkyu/151106.html)
- [ ] 2017年6月データ: 公開待ち

**Comment by yuuki0xff** [comment]
archive.orgに過去のバージョンが保存されているようです。
https://web.archive.org/web/*/http://www.mhlw.go.jp/kinkyu/dl/170510-01.pdf

**Comment by nyampire** [comment]
情報ありがとうございます、見つかりました！

**Comment by nyampire** [comment]
変換して追記したのでClose

57398deb19a2087a24638cad643ef7fb3b77f9bb
