### ISSUE TITLE
お作りのデータを使用させてください

### ISSUE THREAD

**Issue by gh640** [nyampire/jp_labor_act_illegal_list#13]
@nyampire さん

はじめまして。突然のコメントで失礼いたします。

厚生労働省公開の「労働基準関係法令違反に係る公表事案」に興味を持ち、検索でこちらのリポジトリにたどり着きました。

大変有益なデータを整理していただきありがとうございます :)

今回、まとめていらっしゃる tsv ファイル `company_list_20170201_to_20180131.tsv` をベースに、次のページ（とリポジトリ）を作ってみました。

- https://gh640.github.io/japan-noncompliant-companies
- https://github.com/gh640/japan-noncompliant-companies

README 内のライセンスについての説明（ CC0 1.0 であること）と過去のイシュー等には目を通した上で「問題ないのではないか」と思いデータを使用させていただいたのですが、私の見落とし等で何か問題があるかもしれません。もしよろしければ、ご確認いただき、お気づきの点がございましたらコメントでお知らせいただけますと幸いです。

よろしくお願いいたします 😃

**Comment by nyampire** [comment]
いいですね！
こちらのライセンス的には全く問題ありません。こちらの整形は一部手動で行っていますので、使ってみていただいて、もし間違いがありましたらお知らせいただけると嬉しいです。

**Comment by gh640** [comment]
ご返信いただきありがとうございます。

そうですか、ありがとうございます！

はい、今のところ特に間違いなどはないように思っていますが、もし何か見つけましたらご報告させていただきますね :)
