### ISSUE TITLE
追加であるといいかもしれないカラムの検討

### ISSUE THREAD

**Issue by nyampire** [nyampire/jp_labor_act_illegal_list#3]
企業のURLとかあるといいですか

**Comment by Yuutakasan** [comment]
あると嬉しいのはこんな感じですかね。

- URL
- データ更新日付
- 住所
- 代表者名
- 資本金
- 代表メールアドレス
- 従業員数
- 業種
- 設立年月日
- 売上

**Comment by nyampire** [comment]
そこまで細かい情報、このCSVファイルの中に必要かな？ 個人的には、それらの情報は、法人番号を紐付けた上で、別のシステム（法人インフォとか帝国データバンク系とかROBINSとか）を参照しに行ったほうが確実な気がします。

データ更新日付とURLくらいはあってもよいかも。

**Comment by nyampire** [comment]
CSVを作る過程で、「その企業を、どこの局がブラック企業指定したか」という情報を落としてしまっているので、改めて追加したほうがよさそう。

**Comment by nyampire** [comment]
このTSVの基本方針として、「厚生労働省がオープンにした情報を冷徹にデータセットにする」という風にしたほうが、利用者の利便性が高いのではないか（余計なことをしないほうがよいのではないか）というふうに判断しています。

なので、このリポジトリでのカラムの追加はしない方向でゆきたい所存です。

**Comment by nyampire** [comment]
[このコメント](https://github.com/nyampire/jp_labor_act_illegal_list/issues/3#issuecomment-320146681) については、このへん 2b5f309cd9eee2b6a814ce026eb213db2ef28a12 のコミットにて対応済み。

**Comment by nyampire** [comment]
https://github.com/nyampire/jp_labor_act_illegal_list/issues/3#issuecomment-322646938
上記の通り方針確定したのでクローズ
