### ISSUE TITLE
READMEを書く

### ISSUE THREAD

**Issue by nyampire** [nyampire/jp_labor_act_illegal_list#5]
せめて、政府標準利用規約のAttributeは書かないとダメ。

**Comment by wata909** [comment]
元情報は、こちらでしょうか？

労働基準関係法令違反に係る公表事案
（平成28年10月１日～平成29年６月30日公表分）
http://www.mhlw.go.jp/kinkyu/dl/170510-01.pdf

**Comment by nyampire** [comment]
はい、そこです。リンクが貼られてるページはここ。

http://www.mhlw.go.jp/kinkyu/151106.html

PDFの公開がどういう更新ルールになっているかわからないのと、原典確認のためにもともとのPDFファイルもリポジトリ内に入れておいたほうが確実な気がしています。

**Comment by nyampire** [comment]
ざっくり書いた

e94c7cea7d29e0c87b743e4915acfdef63c2ba8a
